### ISSUE TITLE
Provide images

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugoBasicExample#32]
As the refactoring continues I am looking into providing a few images for theme demos.

Currently this can be done in two ways:

1. Use https://picsum.photos/ and simply reference a random image via a parameter

2. Host a few placeholder images directly under `/content/` in this repo.

In both cases images will be from Usplash since they provide images that are free (as in beer) to use and distribute without limits see their [licence](https://unsplash.com/license)

So the question is which solution do you prefer: Put images in the repo or use the picsum service?

I think that the picsum service is simpler but as it happens with these services they have the risk of possible tracking and shutting down sometime in the future.

So I am in favor of selecting a few images and hosting them in the repo.

But I also want to hear your opinions before this is addressed.

cc: @digitalcraftsman @bep and anyone else.

**Comment by digitalcraftsman** [comment]
I would be in favor of hosting the images ourselves because of the reasons you already mentioned. And for most usecases Hugo's image processing pipeline should cover most needs like resizing etc.

**Comment by pacollins** [comment]
I agree with @digitalcraftsman on self hosting.

**Comment by onedrawingperday** [comment]
I changed my mind.

As I said  in https://github.com/gohugoio/hugoBasicExample/issues/35#issuecomment-538621561 and https://github.com/gohugoio/hugoBasicExample/issues/34#issuecomment-538621619 due to the complexity of providing content for all the theme demos from this repo adding images in this repo is kind of complicated without too much benefit.

We already advice theme authors to provide a fallback image through their config. So there isn't really much value in adding this. If a theme is dependent on images for some reasons we can whitelist it.

**Comment by Kaligule** [comment]
@onedrawingperday I disagree, providing images would be very helpfull.

1. Seeing how images are built into a theme is an essential part of a theme demo.
2. Almost all of the themes on https://themes.gohugo.io/ do have posts with images in them. If this repo doesn't provide them then every single maintainer has to pick their own.
3. It is not clear what you mean by "the complexity of providing content for all the theme demos from this repo". Couldn't we just put them into the content directory and call it a day? I do not see where the complexity is.

I therefore vote to reopen this issue.

**Comment by onedrawingperday** [comment]
Hello @Kaligule ,

This is an old issue and back then the Hugo Themes Showcase was serving theme demos from the content of this repo. 

As far as I know this is no longer the case today.

Therefore it would be best if you opened a new issue explaining your request to get a proper response from the current maintainers.
