### ISSUE TITLE
Translated Posts

### ISSUE THREAD

**Issue by pacollins** [gohugoio/hugoBasicExample#51]
It would be ideal if there were translated posts for the most common languages to properly showcase multilingual themes. Not to volunteer someone, but @VincentTam could probably do some quick translations of the posts to at least French and Chinese. Additionally, it would be ideal to have at least one post that does _not_ have a translation so users can see how that would look on their site.

**Comment by onedrawingperday** [comment]
Hm... I investigated about the use of Hugo's multilingual features with the hugoBasicExample a few months back and I am afraid that this is not possible due to https://github.com/gohugoio/hugo/issues/5662

**Comment by VincentTam** [comment]
I'm glad that I see @onedrawingperday's reply before I've actually started the work.  Now, I can concentrate on i18n work of Hugo Future Imperfect Slim and Hugo Swift Theme.

**Comment by onedrawingperday** [comment]
I am closing this issue since it's been left open for a while.

Perhaps if/when  gohugoio/hugo#5662 is resolved we might revisit this.
