### ISSUE TITLE
Duplicated pages in taxonomy list page (because of symlinks)

### ISSUE THREAD

**Issue by Vimux** [gohugoio/hugoBasicExample#52]
**Steps to reproduce:**

1. Open taxonomy list page in theme demo from [themes.gohugo.io](https://themes.gohugo.io) site, for example [Binario markdown tag page](https://themes.gohugo.io//theme/Binario/tags/markdown).
Other examples: [1](https://themes.gohugo.io/theme/hugo-swift-theme/tags/markdown), [2](https://themes.gohugo.io/theme/hermit/tags/markdown), [3](https://themes.gohugo.io//theme/ghostwriter/tags/markdown/), [4](https://themes.gohugo.io//theme/hugo-theme-zen/tags/markdown).

**Screenshot:**

![Screen Shot 2019-08-20 at 11 31 05](https://user-images.githubusercontent.com/21033483/63450303-b2831780-c40f-11e9-9ff9-f5a0d028e091.png)

It looks like due to the symlinks in the [posts](https://github.com/gohugoio/hugoBasicExample/tree/master/content/posts) folder.

---

I've tested this on my Mac with [hugoBasicExample](https://github.com/gohugoio/hugoBasicExample):

* v0.57.2/extended: duplicated pages
* v0.56.3: no duplicated pages

I don't know how Hugo works with symlinks, but it looks like something changed.

**Comment by onedrawingperday** [comment]
Hello thanks for opening the issue.

I have been aware of the page duplication in some theme demos (not all) since Hugo v.0.57.0 and will look into it as soon as my schedule allows.

**Comment by onedrawingperday** [comment]
@Vimux 

This issue was resolved. Deployed demos on the Hugo Themes Showcase no longer display duplicate content on taxonomy lists.
