### ISSUE TITLE
KaTeX inline math being rendered as block (with Goldmark)

### ISSUE THREAD

**Issue by sephore** [gohugoio/hugoBasicExample#60]
According to @onedrawingperday in https://github.com/gohugoio/hugoBasicExample/issues/57#issuecomment-632900551 Goldmark is now able to render the Math Typesetting example, but apparently it shares one same problem with Blackfriday where inline math will be rendered as a block.

Digging the forums, the previous recommendation was simply "use mmark instead" (see: https://discourse.gohugo.io/t/katex-inline-math-in-md-vs-mmark/19141/2).

Am I missing something?

**Comment by onedrawingperday** [comment]
@sephore 

See:  f6f3d29 for current workaround. 

mmark is deprecated and will be removed.

Inline shortcodes require the `unsafe = true` setting for Goldmark.
