### ISSUE TITLE
Multilingual Example

### ISSUE THREAD

**Issue by Arty2** [gohugoio/hugoBasicExample#65]
I would like to propose the addition of a second language to the hugoBasicExample. I am glad to contribute with Greek translations.

This will help in determining which themes support multilingual functionalities. Hopefully this wouldn't cause any compatibility issues with themes that do not.

**Comment by rayjolt** [comment]
I made a multilingual example in a different repo, if that helps: https://github.com/rayjolt/hugo-multilingual-example.
