### ISSUE TITLE
how can i deploy it to github or gitlab i tried abolult 3 hours and i faild

### ISSUE THREAD

**Issue by plus9a** [gohugoio/hugoBasicExample#75]
https://github.com/kazi-sifat-plus9a/blog.github.io.git
https://gitlab.com/kazi-sifat-plus9a/blog.gitlab.io

**gitlab pipelines error **

`Checking out e5c64e79 as master...

Updating/initializing submodules recursively with git depth set to 50...
Executing "step_script" stage of the job script
Using docker image sha256:af2fb5a209c9cb1a4febee5471e6e8383020f94302bf51d1d6413371cee6ce12 for registry.gitlab.com/pages/hugo:latest with digest registry.gitlab.com/pages/hugo@sha256:ec905fcdaf3b882cb3fc4b19b55b7151a12d28519ceaa6c783a079a6db983979 ...
$ hugo server
Error: module "hugo-theme-stack" not found; either add it as a Hugo Module or store it in "/builds/kazi-sifat-plus9a/Blog/themes".: module does not exist
Cleaning up project directory and file based variables
ERROR: Job failed: exit code 255

`

**Comment by Ratikant-rout** [comment]
I can Give You Some Ideas . Can you Assign Me This Work?
