### ISSUE TITLE
This 'example' is very broken

### ISSUE THREAD

**Issue by reubenscratton** [gohugoio/hugoBasicExample#87]
Installing all themes errors out when it reaches `hugo-grapes` because that submodule no longer exists.

Even if you do install all the themes, none of them seem to actually work - all Page Not Found with lots of this sort of thing in the console: 

`WARN  found no layout file for "html" for layout "archives" for kind "page"`

**Comment by coliff** [comment]
This repo should be archived now I think. See: https://github.com/gohugoio/hugoBasicExample/issues/83
